services:

# Service de rendu des différents blocs
    olix.admin.renderer:
        class: Olix\AdminBundle\Twig\AdminRenderer
        arguments: [ "@service_container" ]
# Extension TWIG
    olix.admin.twig.extension.admin:
        class: Olix\AdminBundle\Twig\Extension\AdminExtension
        arguments: [ "@olix.admin.renderer" ]
        tags:
            - { name: twig.extension }
