services:

# Service de rendu de l'admin
    olix.admin:
        class: Olix\AdminBundle\Renderer\AdminRenderer
        arguments: [ "@service_container" ]
# Extension TWIG
    olix.admin.twig.extension.admin:
        class: Olix\AdminBundle\Twig\Extension\AdminExtension
        tags:
            - { name: twig.extension }
# Extension des formulaires
    olix.admin.form.extension.help:
        class: Olix\AdminBundle\Form\HelpFormExtension
        tags:
            - { name: form.type_extension, alias: form }
