###
# Route pour la sécurité
##
olix_admin_security:
    resource: "@OlixSecurityBundle/Resources/config/routing.yml"

###
# JS routing
##
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"